# Generated by Django 5.2.6 on 2026-03-15 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_projectfile_projectnote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='projectfile',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='projectnote',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-created_at']},
        ),
    ]
